image:
  file: .gitpod.Dockerfile

# Workspace startup
tasks:
  - init: npm install
    command: npm start
  - openMode: tab-after
    command: clear && .tutorial/start.sh

# Ports to expose on workspace
ports:
  - port: 3000
    onOpen: ignore
